### ISSUE TITLE
dc_irisftpsample.Country  is missing from REPO

### ISSUE THREAD

**Issue by rcemper** [yurimarx/iris-ftp-sample#1]
Hi Yuri,

Install and start works great
But dc_irisftpsample.Country you refer in Demo is  missing

**Comment by yurimarx** [comment]
It is created only when you put countries.csv file on FTP server, because csvgen will generate the class on the fly and load the csv data on it

**Comment by rcemper** [comment]
Thanks!  that gave me the file and class
BUT: - no data.
Debugging CSVGEN  I realized that LOAD DATA failed:
%Message = "Fehler **#5023: Java-Gateway-Fehler: Connection cannot be established"**   
Disabling UseLoadData in LoadCSVFTPBusinessOperation  solved the problem and I got my data
